import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const source = fs.readFileSync(new URL('../src/views/OutfitLookbook.jsx', import.meta.url), 'utf8')
const css = fs.readFileSync(new URL('../src/App.css', import.meta.url), 'utf8')

test('OutfitLookbook exposes indoor season in filters and edit form', () => {
  assert.match(source, /value:\s*'indoor',\s*label:\s*'🏠 Indoor \/ Any Weather'/)
  assert.match(source, /const OUTFIT_SEASONS = \[/)
  assert.match(source, /Indoor is intentionally preserved as an outfit season\/environment value/)
  assert.match(source, /value:\s*'indoor',\s*label:\s*'indoor'/)
})

test('OutfitForm edit mode prepopulates fields and submits PUT to the outfit endpoint', () => {
  assert.match(source, /function OutfitForm\(\{ outfit = null, onSave, onCancel \}\)/)
  assert.match(source, /const isEdit = Boolean\(outfit\)/)
  assert.match(source, /useState\(outfit\?\.name \|\| ''\)/)
  assert.match(source, /useState\(outfit\?\.occasion \|\| 'casual'\)/)
  assert.match(source, /useState\(outfit\?\.season \|\| 'year-round'\)/)
  assert.match(source, /useState\(outfit\?\.notes \|\| ''\)/)
  assert.match(source, /useState\(outfit\?\.status \|\| 'confirmed'\)/)
  assert.match(source, /fetch\(isEdit \? `\/api\/outfits\/\$\{outfit\.id\}` : '\/api\/outfits'/)
  assert.match(source, /method: isEdit \? 'PUT' : 'POST'/)
  assert.match(source, /className="modal-sheet outfit-form-sheet"/)
  assert.match(source, /aria-labelledby="outfit-form-title"/)
  assert.match(source, /id="outfit-form-title"/)
  assert.match(source, /className="modal-handle outfit-form-handle"/)
  assert.match(source, /className="photo-preview outfit-form-preview"/)
  assert.match(source, /alt="Outfit preview"/)
  assert.match(source, /<span className="form-helper">Choose one<\/span>/)
  assert.match(css, /\.outfit-form-preview img[\s\S]*object-fit: contain/)
  assert.match(css, /@media \(min-width: 768px\)[\s\S]*\.outfit-form-handle[\s\S]*display: none/)
  assert.match(css, /\.outfit-form-sheet \.chip-toggle\.active,[\s\S]*\.outfit-form-sheet \.radio-btn\.active[\s\S]*background: var\(--accent\)/)
})

test('OutfitDetail opens the shared form for editing', () => {
  assert.match(source, /function OutfitDetail\(\{ outfit, onClose, onEdit, onDelete/)
  assert.match(source, /className="outfit-overflow-menu" role="menu"/)
  assert.match(source, />\s*Edit outfit\s*<\/button>/)
  assert.match(source, /onEdit\(\{ \.\.\.outfit, pieces, main_piece_id: mainPieceId \}\)/)
  assert.match(source, /onEdit=\{outfit => \{ setDetail\(null\); setEditOutfit\(outfit\); setShowForm\(true\) \}\}/)
  assert.match(source, /<OutfitForm outfit=\{editOutfit\}/)
})

test('Piece selector supports marking a linked outfit piece as Main', () => {
  assert.match(source, /function PieceSelector\(\{ outfitId, linkedPieceIds, mainPieceId = null/)
  assert.match(source, /body: JSON\.stringify\(\{ pieceIds: selectedIds, mainPieceId: nextMainId \}\)/)
  assert.match(source, /e\.preventDefault\(\)/)
  assert.match(source, /e\.stopPropagation\(\)/)
  assert.match(source, /setMainId\(isMain \? null : pieceId\)/)
  assert.match(source, /const isMain = mainId === pieceId/)
  assert.match(source, />\s*Main\s*<\/button>/)
  assert.match(source, /main_piece_id: mainPieceId/)
})

test('Similar outfit actions request wardrobe formula variants', () => {
  assert.match(source, /variantMode: 'formula'/)
  assert.match(source, /Create formula-similar outfits from my wardrobe based on this saved look\./)
  assert.doesNotMatch(source, /variantMode: 'similar'/)
})

test('Outfit cards open detail directly and keep actions inside the modal', () => {
  assert.doesNotMatch(source, /outfit-card-action/)
  assert.doesNotMatch(css, /outfit-card-action/)
  assert.match(source, /onClick=\{event => openOutfitDetail\(o, event\)\}/)
  assert.match(source, /onKeyDown=\{event => handleCardKeyDown\(event, \(\) => openOutfitDetail\(o, event\)\)\}/)
  assert.match(source, /role="button"/)
  assert.match(source, /tabIndex=\{0\}/)
  assert.match(source, /aria-label=\{`Open \$\{o\.name \|\| 'outfit'\} outfit`\}/)
  assert.match(source, /e\.stopPropagation\(\); handleFav\(o\)/)
  assert.match(source, />\s*Critique outfit\s*<\/button>/)
  assert.match(css, /\.outfit-card:focus-visible/)
})

test('Outfit detail modal separates identity, composition, and styling actions', () => {
  assert.match(source, /className="modal-sheet outfit-detail-sheet"/)
  assert.match(source, /className="outfit-detail-close"/)
  assert.match(source, /aria-label="Outfit identity"/)
  assert.match(source, /aria-label="Outfit composition"/)
  assert.match(source, /aria-label="Styling actions"/)
  assert.match(source, /className="outfit-linked-pieces"/)
  assert.match(source, /className="outfit-linked-piece-photo"/)
  assert.match(source, /className="outfit-action-primary"/)
  assert.match(source, />\s*Critique outfit\s*<\/button>/)
  assert.match(source, />\s*Similar variants\s*<\/button>/)
  assert.match(source, />\s*Creative alternatives\s*<\/button>/)
  assert.match(source, />\s*◇ Ask a custom question\s*<\/button>/)
  assert.match(source, />\s*Delete outfit\s*<\/button>/)
  assert.doesNotMatch(source, />\s*Find similar\s*<\/button>/)
  assert.doesNotMatch(source, />\s*Create variation\s*<\/button>/)
  assert.match(source, /requestAnimationFrame\(\(\) => outfitCardFocusRef\.current\?\.focus\?\.\(\)\)/)
  assert.match(css, /\.outfit-detail-section/)
  assert.match(css, /\.outfit-overflow-menu/)
  assert.match(css, /\.outfit-action-secondary-row/)
})

test('Lookbook header uses compact tabs, filter menus, and removable active chips', () => {
  assert.match(source, /const \[openFilterMenu, setOpenFilterMenu\]/)
  assert.match(source, /className="lookbook-pin-toggle"/)
  assert.match(source, />\s*All outfits\s*<\/button>/)
  assert.match(source, />\s*Pinned\s*<\/button>/)
  assert.match(source, /className="subtab-count"/)
  assert.match(source, /placeholder="Search outfits\.\.\."/)
  assert.match(source, /className="lookbook-filter-toolbar"/)
  assert.match(source, /setOpenFilterMenu\(openFilterMenu === 'occasion' \? null : 'occasion'\)/)
  assert.match(source, /setOpenFilterMenu\(openFilterMenu === 'season' \? null : 'season'\)/)
  assert.match(source, /className="active-filter-row"/)
  assert.match(source, /className="active-filter-chip"/)
  assert.match(source, /Clear all/)
  assert.doesNotMatch(source, /occ-filter-row/)
  assert.doesNotMatch(source, /season-filter-row/)
  assert.match(css, /\.lookbook-filter-toolbar/)
  assert.match(css, /\.filter-menu-popover/)
  assert.match(css, /\.active-filter-row/)
})

test('indoor season matches warm, cool, and year-round browsing but can be filtered directly', () => {
  assert.match(source, /if \(selectedSeason === 'indoor'\) return outfitSeason === 'indoor'/)
  assert.match(source, /if \(selectedSeason === 'year-round'\) return outfitSeason === 'year-round' \|\| outfitSeason === 'indoor'/)
  assert.match(source, /return outfitSeason === selectedSeason \|\| outfitSeason === 'year-round' \|\| outfitSeason === 'indoor'/)
})

test('Generated Outfits board images are normalized before rendering and critique handoff', () => {
  assert.match(source, /const resolveUploadImageSrc = \(photo\) =>/)
  assert.ok(source.includes("value.replace(/^\\/uploads\\/+uploads\\//, '/uploads/')"))
  assert.match(source, /value\.startsWith\('generated-boards\/'\)/)
  assert.match(source, /const uploadsIndex = value\.indexOf\('\/uploads\/'\)/)
  assert.match(source, /const boardImageSrc = resolveUploadImageSrc\(board\.image_url\)/)
  assert.match(source, /src=\{boardImageSrc\}/)
  assert.match(source, /src=\{resolveUploadImageSrc\(b\.image_url\)\}/)
  assert.match(source, /photo: resolveUploadImageSrc\(board\.image_url\)/)
})
